import React from "react";
import { useInView } from "react-intersection-observer";
import portada from "../../assets/portadaCap1.png";
const AboutUs2 = () => {
  const [ref1, inView1] = useInView({
    triggerOnce: true,
    threshold: 0.5,
  });
  const [ref2, inView2] = useInView({
    triggerOnce: true,
    threshold: 0.5,
  });
  const [ref3, inView3] = useInView({
    triggerOnce: true,
    threshold: 0.5,
  });
  const [ref4, inView4] = useInView({
    triggerOnce: true,
    threshold: 0.5,
  });
  return (
    <div className="py-20">
      <div className="flex flex-wrap justify-center items-center px-4 lg:px-10">
        <div className="w-full flex flex-wrap justify-center items-center gap-y-4">
          <div
            className="w-full lg:w-1/2 flex flex-wrap text-left text-gray-200 poppins-400 text-xl space-y-4 px-4 lg:px-32"
            ref={ref2}
          >
            <div>
              <h1
                className={`${
                  inView2
                    ? "opacity-100 transition-opacity duration-[1s]"
                    : "opacity-0"
                } text-xl`}
              >
               We stand out for being 100% focused on e-commerce for over 5 years.
              </h1>
            </div>
            <div>
              <h1
                className={`${
                  inView2
                    ? "opacity-100 transition-opacity duration-[1s]"
                    : "opacity-0"
                } text-xl`}
              >
              This allows us to follow a step-by-step approach of proven strategies that we know work in the market.
              </h1>
            </div>
            <div>
              <h1
                className={`${
                  inView2
                    ? "opacity-100 transition-opacity duration-[1s]"
                    : "opacity-0"
                } text-xl`}
              >
               Additionally, we create a new sales channel for your company through this formula, where our compensation is exclusively based on the results obtained from the profits generated by this funnel.
              </h1>
            </div>
            <div>
              <h1
                className={`${
                  inView2
                    ? "opacity-100 transition-opacity duration-[1s]"
                    : "opacity-0"
                } text-xl`}
              >
                We also complement your current marketing team by taking on different tasks.
              </h1>
            </div>
            <div>
              <h1
                className={`${
                  inView2
                    ? "opacity-100 transition-opacity duration-[1s]"
                    : "opacity-0"
                } text-xl`}
              >
               This distinction lies in the fact that we do not offer common services like any other agency;
              </h1>
            </div>
            <div className="w-full flex justify-center lg:justify-start"
            ref={ref4}
            >
              <a href="#calendly">
                <button className={`${
                  inView4
                    ? "opacity-100 transition-opacity duration-[1s]"
                    : "opacity-0"
                } w-auto text-2xl font-poppins-400 text-white border-2 border-white rounded-3xl py-2 px-4 hover:bg-white hover:text-purple-900 transition duration-400`}>
                  Agendar Demo
                </button>
              </a>
            </div>
          </div>
          <div className="w-full lg:w-1/2"
          ref={ref3}
          >
            <img
              className={`${
                inView3
                  ? "opacity-100 transition-opacity duration-[1s]"
                  : "opacity-0"
              } w-full`}
              src={portada}
              alt="img-ds"
            />
          </div>
        </div>
      </div>
    </div>
  );
};

export default AboutUs2;
